import random
import time


class RandomUtils:
    @staticmethod
    def generate_run_name(basename: str | None = None, use_local_random: bool = True) -> str:
        if use_local_random:
            local_random = random.Random(time.time_ns())
            random_number = local_random.randint(1, 9999)
        else:
            local_random = None
            random_number = random.randint(1, 9999)
        noun = RandomUtils.generate_noun(local_random)
        adjective = RandomUtils.generate_adjective(local_random)
        # Generate a random number

        if basename is None:
            return f"{adjective}-{noun}-{random_number}"
        return f"{basename}-{adjective}-{noun}-{random_number}"

    @staticmethod
    def generate_adjective(local_random: random.Random | None = None) -> str:
        adjectives = [
            "bamboozled",
            "discombobulated",
            "flabbergasted",
            "kerfuffled",
            "gobsmacked",
            "higgledy-piggledy",
            "topsy-turvy",
            "willy-nilly",
            "helter-skelter",
            "shilly-shally",
            "zany",
            "wacky",
            "bonkers",
            "kooky",
            "loopy",
            "nutty",
            "batty",
            "cuckoo",
            "daffy",
            "goofy",
            "loony",
            "screwy",
            "wacko",
            "bizarro",
            "kookaburra",
            "flapdoodle",
            "skedaddling",
            "flummoxed",
            "befuddled",
            "cattywampus",
            "spiffy",
            "jazzy",
            "snazzy",
            "ritzy",
            "swanky",
            "posh",
            "schmancy",
            "hoity-toity",
            "la-di-da",
            "fancy-schmancy",
            "whizbang",
            "hodgepodge",
            "ragamuffin",
            "rapscallion",
            "scalawag",
            "whippersnapper",
            "nincompoop",
            "flibbertigibbet",
            "namby-pamby",
            "wishy-washy",
            "dilly-dallying",
            "tootling",
            "gallivanting",
            "lollygagging",
            "moseying",
            "meandering",
            "dawdling",
            "shimmying",
            "jiggling",
            "wiggling",
            "squiggling",
            "jiving",
            "grooving",
            "boogying",
            "discombobulating",
            "flabbergasting",
            "mind-boggling",
            "stupefying",
            "bamboozling",
            "flummoxing",
            "bewildering",
            "perplexing",
            "confounding",
            "baffling",
            "mystifying",
            "skedaddled",
            "absquatulated",
            "vamoosed",
            "scampered",
            "hightailed",
            "scooted",
            "moseyed",
            "ambled",
            "meandered",
            "shuffled",
            "schlepped",
            "tottered",
            "wobbled",
            "zigzagged",
            "ricocheted",
            "ping-ponged",
            "yo-yoed",
            "seesawed",
            "flip-flopped",
            "topsy-turvied",
            "upside-downed",
            "inside-outed",
            "backwards-forwarded",
            "twisted",
            "pretzel-shaped",
            "noodly",
            "spaghetti-like",
            "wiggly-wobbly",
            "squiggly-squaggly",
            "loopy-doopy",
            "curlicued",
            "spiraled",
            "corkscrewed",
            "helixed",
            "labyrinthine",
            "convoluted",
            "serpentine",
            "meandering",
            "roundabout",
            "circuitous",
            "tortuous",
            "winding",
            "twisty-turny",
            "loopy-de-loop",
            "rollercoastery",
            "whirly-twirly",
            "dipsy-doodle",
            "higgledy-piggledy",
            "topsy-turvy",
            "hurly-burly",
            "hodge-podge",
            "jumbled",
            "muddled",
            "scrambled",
            "tangled",
            "disheveled",
            "mussed",
            "rumpled",
            "frazzled",
            "frayed",
            "flustered",
            "rattled",
            "ruffled",
            "discombobulated",
        ]

        if local_random is not None:
            return local_random.choice(adjectives)
        return random.choice(adjectives)

    @staticmethod
    def generate_noun(local_random: random.Random | None = None) -> str:
        nouns = [
            "whisperer",
            "wrangler",
            "guru",
            "ninja",
            "jedi",
            "wizard",
            "sorcerer",
            "unicorn",
            "sasquatch",
            "yeti",
            "dragon",
            "narwhal",
            "bacon",
            "pickle",
            "llama",
            "burrito",
            "sombrero",
            "mustache",
            "kazoo",
            "ukulele",
            "disco-ball",
            "taco",
            "flamingo",
            "pineapple",
            "banjo",
            "mocktail",
            "boomerang",
            "lasso",
            "yo-yo",
            "frisbee",
            "hula-hoop",
            "didgeridoo",
            "bowtie",
            "top-hat",
            "monocle",
            "handlebar",
            "accordion",
            "bagpipe",
        ]

        if local_random is not None:
            return local_random.choice(nouns)
        return random.choice(nouns)
