# Set DOCS_FOLDER env var (e.g. absolute path to documents directory)
path: ${oc.env:DOCS_FOLDER}/2023.07.20.549210v2.full.pdf
encoding: utf-8
group_id: test-graph
source_description: Impaired biogenesis of basic proteins impacts multiple hallmarks of the aging brain
reference_year: 2023
source_type: pdf
lang: en
