# Set DOCS_FOLDER env var (e.g. absolute path to documents directory)
path: ${oc.env:DOCS_FOLDER}/paris.txt
encoding: utf-8
group_id: test-graph
source_description: This is a document about Paris
reference_year: 2026
source_type: text
lang: en
