# conf/config.yaml
defaults:
  - _self_

hydra:
  run:
    dir: .hydra-outputs

# Main configuration for DataProcessorConfig
name: dummy
library: pyspark
storage: local
data_files:
  relations:         
    - path: "data/test/test_relations.tsv"
      sep: "\t"
      column_names: ["pmid", "subject_id", "object_id", "relation_type", "confidence"]
      header: true
      encoding: "utf-8"

output_path: data/output
output_sep: "\t"
spark_builder: null
spark:
  app_name: Dummy_Processor_Spark
  master: local[*]
  configs:
    spark.executor.memory: 2g
    spark.driver.memory: 1g
