sweep:
  dir: outputs/hpo/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}
sweeper:
  _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 5
  direction: maximize
  study_name: ${run.project}
  n_trials: 60
  n_jobs: 1   
  params:
    optimizer.kwargs.lr: choice(0.001, 0.01, 0.1)
    model.config.embedding_dim: choice(32, 64, 128)
    negative_sampler.config.num_negatives: choice(1)  
    model.config.gnn_config.activation: choice(lrelu)
    model.config.gnn_config.dropout: choice(0.0, 0.1, 0.3, 0.5)
    model.config.gnn_config.batch_norm: choice(False, True)
    model.config.gnn_config.num_layers_pre: choice(0)
    model.config.gnn_config.num_layers_gnn: choice(2)
    model.config.gnn_config.num_layers_post: choice(0)