name: RankingRelationLoss
kwargs:
  entity_loss: MarginRankingLoss
  entity_loss_kwargs:
    margin: 1.0
    reduction: mean
  relation_loss: BCEWithLogitsLoss
  relation_loss_kwargs:
    reduction: mean
  neg_strategy: hardest
  rel_loss_weight: 1.0
  entity_loss_multi_neg: false
