_target_: kge.data_processor.KGDataProcessor
config:
  _target_: kge.data_processor.KGDataProcessorConfig
  loader:
    batch_size: 1024
    num_workers: 15
    persistent_workers: False
    pin_memory: False