_target_: kge.data_processor.KGDataProcessor
config:
  _target_: kge.data_processor.KGDataProcessorConfig
  loader:
    num_neighbors: [512, 512]
    batch_size: 8912
    num_batches_for_scaling: 10
    negs_per_pos: 1
    corrupt_probs: [0.4, 0.2, 0.4]
    shuffle: True
    scaler_path: ${oc.env:CACHED_DATA_FOLDER}target_scaler.json
    pin_memory: True
    num_workers: 16