//TODO : Replace dummy data for actual references
export const candidateData = {
  context:
    'The essence of Lorem Ipsum, as we know it today, draws from the writings of the celebrated ancient Roman philosopher Cicero — but with a creative twist. Rather than a direct translation or faithful reproduction, the text has been intentionally scrambled and modified. By scrambling the words and rearranging the letters, designers and typesetters ensured that the filler text would be devoid of any recognizable meaning. This served the purpose of preventing readers from becoming distracted by the content itself and instead focusing on the design, layout, and typography. In essence, Lorem Ipsum allowed the form to take precedence over the content, a principle that remains vital in the visual arts to this day.',
  references: [
    {
      title: 'The reference of the year',
      publication: 'Lorem ipsum',
      year: '2022',
      citation: '183',
      score: '0.99999',
      abstract: [
        'Lorem ipsum (/ˌlɔː.rəm ˈɪp.səm/ LOR-əm IP-səm) is a dummy or placeholder text commonly used in graphic design, publishing, and web development to fill empty spaces in a layout that does not yet have content.',
        'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        'Versions of the Lorem ipsum text have been used in typesetting at least since the 1960s, when it was popularized by advertisements for Letraset transfer sheets.[1] Lorem ipsum was introduced to the digital world in the mid-1980s, when Aldus employed it in graphic and word-processing templates for its desktop publishing program PageMaker. Other popular word processors, including Pages and Microsoft Word, have since adopted Lorem ipsum,[2] as have many LaTeX packages,[3][4][5] web content managers such as Joomla! and WordPress, and CSS libraries such as Semantic UI.',
        'But the real secrets of its origin are revealed in its sixth word, consectetur, which happens to be the third-person singular present active subjunctive of the deponent Latin verb consector, which means “to pursue eagerly.” Helpfully, it’s a rare enough form that there aren’t many examples of it in the existing corpus of Latin, so it’s not hard to trace it back to its original context. Credit for figuring this out (some time in the ’90s) goes to Classics professor Richard McClintock, who sent in a correction to a magazine that had run an article defining Lorem Ipsum the same way it was originally explained to me: “It’s not Latin, though it looks like it, and it actually says nothing.” McClintock’s note indisputably pinpointed the source of Lorem Ipsum, but in the process introduced a red herring that has plagued almost everyone who’s written about it since.',
        'Lorem ipsum (/ˌlɔː.rəm ˈɪp.səm/ LOR-əm IP-səm) is a dummy or placeholder text commonly used in graphic design, publishing, and web development to fill empty spaces in a layout that does not yet have content.',
        'Lorem ipsum is typically a corrupted version of De finibus bonorum et malorum, a 1st-century BC text by the Roman statesman and philosopher Cicero, with words altered, added, and removed to make it nonsensical and improper Latin. The first two words themselves are a truncation of dolorem ipsum ("pain itself").',
        'Versions of the Lorem ipsum text have been used in typesetting at least since the 1960s, when it was popularized by advertisements for Letraset transfer sheets.[1] Lorem ipsum was introduced to the digital world in the mid-1980s, when Aldus employed it in graphic and word-processing templates for its desktop publishing program PageMaker. Other popular word processors, including Pages and Microsoft Word, have since adopted Lorem ipsum,[2] as have many LaTeX packages,[3][4][5] web content managers such as Joomla! and WordPress, and CSS libraries such as Semantic UI.',
        'But the real secrets of its origin are revealed in its sixth word, consectetur, which happens to be the third-person singular present active subjunctive of the deponent Latin verb consector, which means “to pursue eagerly.” Helpfully, it’s a rare enough form that there aren’t many examples of it in the existing corpus of Latin, so it’s not hard to trace it back to its original context. Credit for figuring this out (some time in the ’90s) goes to Classics professor Richard McClintock, who sent in a correction to a magazine that had run an article defining Lorem Ipsum the same way it was originally explained to me: “It’s not Latin, though it looks like it, and it actually says nothing.” McClintock’s note indisputably pinpointed the source of Lorem Ipsum, but in the process introduced a red herring that has plagued almost everyone who’s written about it since.',
      ],
    },
    {
      title: 'Bio something something',
      publication: 'Lorem ipsum',
      year: '2024',
      citation: '95',
      score: '0.9879',
      abstract: [
        `The Lorem ipsum text is derived from sections 1.10.32 and 1.10.33 of Cicero's De finibus bonorum et malorum.[6][7] The physical source may have been the 1914 Loeb Classical Library edition of De finibus, where the Latin text, presented on the left-hand (even) pages, breaks off on page 34 with "Neque porro quisquam est qui do-" and continues on page 36 with "lorem ipsum ...", suggesting that the galley type of that page was mixed up to make the dummy text seen today.`,
        `The discovery of the text's origin is attributed to Richard McClintock, a Latin scholar at Hampden–Sydney College. McClintock connected Lorem ipsum to Cicero's writing sometime before 1982 while searching for instances of the Latin word consectetur, which was rarely used in classical literature.[2] McClintock first published his discovery in a 1994 letter to the editor of Before & After magazine,[8] contesting the editor's earlier claim that Lorem ipsum held no meaning.[2]`,
        `As Cicero puts it, “The wise man always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.” It’s a statement that still crops up in some of the weirdest places.
        Nowadays, there’s no shortage of Lorem Ipsum alternatives, including Nietzsche Ipsum, Delorean Ipsum, Pirate Ipsum, Cheese Ipsum, Cat Ipsum, and DJ Khaled Ipsum. I’d argue that there’s nothing quite as elegant as butchered Cicero if you have an urge to accidentally publish dummy text, but there are plenty of genuinely delightful alternatives to choose from`,
        `The Lorem ipsum text is derived from sections 1.10.32 and 1.10.33 of Cicero's De finibus bonorum et malorum.[6][7] The physical source may have been the 1914 Loeb Classical Library edition of De finibus, where the Latin text, presented on the left-hand (even) pages, breaks off on page 34 with "Neque porro quisquam est qui do-" and continues on page 36 with "lorem ipsum ...", suggesting that the galley type of that page was mixed up to make the dummy text seen today.`,
        `The discovery of the text's origin is attributed to Richard McClintock, a Latin scholar at Hampden–Sydney College. McClintock connected Lorem ipsum to Cicero's writing sometime before 1982 while searching for instances of the Latin word consectetur, which was rarely used in classical literature.[2] McClintock first published his discovery in a 1994 letter to the editor of Before & After magazine,[8] contesting the editor's earlier claim that Lorem ipsum held no meaning.[2]`,
        `As Cicero puts it, “The wise man always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.” It’s a statement that still crops up in some of the weirdest places.
        Nowadays, there’s no shortage of Lorem Ipsum alternatives, including Nietzsche Ipsum, Delorean Ipsum, Pirate Ipsum, Cheese Ipsum, Cat Ipsum, and DJ Khaled Ipsum. I’d argue that there’s nothing quite as elegant as butchered Cicero if you have an urge to accidentally publish dummy text, but there are plenty of genuinely delightful alternatives to choose from`,
      ],
    },
    {
      title: 'Scientific science paper',
      publication: 'Lorem ipsum',
      year: '1990',
      citation: '275',
      score: '0.5679',
      abstract: [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng] velit',
        `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, 
        omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng] velit',
        `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, 
        omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`,
      ],
    },
  ],
};
