defaults:
  - _self_
  - path_finder: default
  - explainer: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

log_level: INFO 


run:
  device: cuda


hydra:
  run:
    dir: .
  output_subdir: null